# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-22 03:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20161122_0204'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='birthdate',
            field=models.DateField(default=datetime.datetime(2016, 11, 22, 3, 7, 48, 166274, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
