# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-10 00:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_profile_creditcard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='creditCard',
            field=models.PositiveSmallIntegerField(),
        ),
    ]
