# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 00:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_auto_20161208_2356'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartproduct',
            name='cart',
        ),
        migrations.AddField(
            model_name='cartproduct',
            name='cart',
            field=models.ManyToManyField(to='cart.Cart'),
        ),
        migrations.AlterField(
            model_name='cartproduct',
            name='quantity',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
