# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-09 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_cartproduct_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartproduct',
            name='price',
            field=models.FloatField(default=1),
        ),
    ]
