# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-21 19:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='staff',
            new_name='admin',
        ),
    ]
